version: "3.9"

services:
  web:
    build: .   # usa o Dockerfile que está na raiz do projeto
    container_name: tcc-informatica
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: banco-tcc-informatica
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tccjocelino
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
