services:
  web:
    image: php:8.3.8-apache
    container_name: tcc-informatica
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: banco-tcc-informatica
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
