https://discord.com/api/webhooks/1419457729637908500/82oe341GFj1B3rQMgq3UhQ9Et66sjGS-UQib8dnsiqYdN7SDVcVWlJYmCb-L8iZZu_7d

name: Discord Commit Notification

on:
  push:
    branches:
      - master

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            📌 Novo commit em **${{ github.repository }}**
            Autor: ${{ github.actor }}
            Mensagem: ${{ github.event.head_commit.message }}
            Link: ${{ github.event.head_commit.url }}
